### ISSUE TITLE
Cannot launch odrfgui

### ISSUE THREAD

**Issue by lwymarie** [Keck-DataReductionPipelines/OsirisDRP#115]
Please see below for what happened what I attempted to execute odrfgui.bat. I already commented out all the lines related to calling the Security Manager in edu.ucla.astro.osiris.drp.odrfgui.ODRFGUI.main. I'm guessing the programs need to be recompiled as I ran the "make all" command during installation, but I'm not familiar with this. 

flemish.local> cd odrfgui/
flemish.local> odrfgui.bat
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:416)
	at edu.ucla.astro.osiris.drp.odrfgui.ODRFGUI.main(ODRFGUI.java:25)

**Comment by lwymarie** [comment]
Update: Issue solved by installing Java version 17 instead of 18.
